name: Check Images and Update Status

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-images:
    runs-on: ubuntu-latest  # Can use Ubuntu as Playwright handles all browsers
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright PyGithub
        pip install -r requirements.txt
        playwright install  # Install all browser engines
        playwright install-deps  # Install browser dependencies

    - name: Run image checker
      run: python image_checker.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Generate HTML report
      run: |
        mkdir -p public
        python generate_report.py

    - name: Create issues for missing images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python create_issues.py
  
    - name: Update README.md
      run: python generate_readme.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git add README.md
        git config --global user.name "GitHub Action"
        git pull
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with latest image check results" && git push)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true